# Статистическое сопоставление цены биткоина с ценами на золото.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
BTC = pd.read_csv('/content/drive/MyDrive/Geekbrains/prob_theory_and_math_stat/BTC.csv')
GOLD = pd.read_csv('/content/drive/MyDrive/Geekbrains/prob_theory_and_math_stat/gold.csv')

In [3]:
BTC

            Дата      Цена     Откр.     Макс.      Мин.   Объём  Изм. %
0     07.07.2023  30.212,3  29.912,7  30.315,8  29.757,4  74,30K   1,00%
1     06.07.2023  29.913,1  30.512,8  31.463,6  29.869,0  90,81K  -1,97%
2     05.07.2023  30.512,8  30.768,6  30.875,6  30.233,3  43,23K  -0,83%
3     04.07.2023  30.768,4  31.152,0  31.326,5  30.657,8  42,12K  -1,23%
4     03.07.2023  31.151,3  30.617,5  31.377,0  30.581,5  56,49K   1,74%
...          ...       ...       ...       ...       ...     ...     ...
4733  22.07.2010       0,1       0,1       0,1       0,1   2,16K   0,00%
4734  21.07.2010       0,1       0,1       0,1       0,1   0,58K   0,00%
4735  20.07.2010       0,1       0,1       0,1       0,1   0,26K   0,00%
4736  19.07.2010       0,1       0,1       0,1       0,1   0,57K   0,00%
4737  18.07.2010       0,1       0,0       0,1       0,1   0,08K   0,00%

[4738 rows x 7 columns]

In [4]:
BTC.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4738 entries, 0 to 4737
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Дата    4738 non-null   object
 1   Цена    4738 non-null   object
 2   Откр.   4738 non-null   object
 3   Макс.   4738 non-null   object
 4   Мин.    4738 non-null   object
 5   Объём   4738 non-null   object
 6   Изм. %  4738 non-null   object
dtypes: object(7)
memory usage: 259.2+ KB

In [5]:
BTC.rename(columns = {'Откр.' : 'BTC open', 'Дата' : 'Date'}, inplace=True)

In [6]:
BTC['BTC open'] = BTC['BTC open'].replace('[.]', '', regex=True).replace('[,]', '.', regex=True).astype(float)

In [7]:
BTC['Date'] = BTC['Date'].replace('[.]', '-', regex=True)

In [22]:
BTC_open = BTC[['Date', 'BTC open']].copy()
BTC_open.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4738 entries, 0 to 4737
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      4738 non-null   object
 1   BTC open  4738 non-null   float64
dtypes: float64(1), object(1)
memory usage: 74.2+ KB

In [23]:
BTC_open['Date'] = BTC_open['Date'].str.split('-').str[::-1].str.join('-')

In [24]:
BTC_open

            Date  BTC open
0     2023-07-07   29912.7
1     2023-07-06   30512.8
2     2023-07-05   30768.6
3     2023-07-04   31152.0
4     2023-07-03   30617.5
...          ...       ...
4733  2010-07-22       0.1
4734  2010-07-21       0.1
4735  2010-07-20       0.1
4736  2010-07-19       0.1
4737  2010-07-18       0.0

[4738 rows x 2 columns]

In [11]:
GOLD

            Date     Open     High     Low    Close  Volume Currency
0     2000-01-04   281.00   281.00   281.0   282.70       4      USD
1     2000-01-05   283.20   283.20   283.2   281.10      16      USD
2     2000-01-06   281.40   281.40   281.4   281.40       0      USD
3     2000-01-07   281.90   281.90   281.9   281.90       0      USD
4     2000-01-10   281.70   281.70   281.7   281.70       0      USD
...          ...      ...      ...     ...      ...     ...      ...
5774  2022-07-21  1693.70  1719.50  1678.4  1713.40       0      USD
5775  2022-07-22  1717.20  1738.30  1711.7  1727.40       0      USD
5776  2022-07-24  1724.35  1725.05  1722.3  1722.55       0      USD
5777  2022-07-25  1726.30  1734.60  1712.9  1719.10       0      USD
5778  2022-07-26  1719.65  1726.30  1718.9  1722.25       0      USD

[5779 rows x 7 columns]

In [12]:
GOLD.rename(columns = {'Open' : 'GOLD open'}, inplace=True)
GOLD_open = GOLD[['Date', 'GOLD open']]
GOLD_open.head()

         Date  GOLD open
0  2000-01-04      281.0
1  2000-01-05      283.2
2  2000-01-06      281.4
3  2000-01-07      281.9
4  2000-01-10      281.7

In [13]:
res1 = BTC_open.merge(GOLD_open, on=["Date"])
res1.head()

         Date  BTC open  GOLD open
0  2022-07-26   21301.6    1719.65
1  2022-07-25   22582.3    1726.30
2  2022-07-24   22449.8    1724.35
3  2022-07-22   23150.0    1717.20
4  2022-07-21   23219.9    1693.70

In [14]:
res1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3143 entries, 0 to 3142
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       3143 non-null   object
 1   BTC open   3143 non-null   float64
 2   GOLD open  3143 non-null   float64
dtypes: float64(2), object(1)
memory usage: 73.8+ KB

In [15]:
res1[['BTC open', 'GOLD open',]].corr()

           BTC open  GOLD open
BTC open   1.000000   0.605892
GOLD open  0.605892   1.000000

Вывод: Мы видим, что корреляция биткоина и золота высокая, это значит направления движения цены вверх или вниз чаще совпадают.

**Проверка не совпадающих дат**

In [18]:
BTC_open['Date'].isin(GOLD_open['Date']).all()
GOLD_open['Date'].isin(BTC_open['Date']).all()

np.False_

In [19]:
(~BTC_open['Date'].isin(GOLD_open['Date'])).sum()
(~GOLD_open['Date'].isin(BTC_open['Date'])).sum()

np.int64(2636)

In [21]:
BTC_open[~BTC_open['Date'].isin(GOLD_open['Date'])].tail(20)

            Date  BTC open
4674  2010-09-19       0.1
4675  2010-09-18       0.1
4681  2010-09-12       0.1
4682  2010-09-11       0.1
4687  2010-09-06       0.1
4688  2010-09-05       0.1
4689  2010-09-04       0.1
4695  2010-08-29       0.1
4696  2010-08-28       0.1
4702  2010-08-22       0.1
4703  2010-08-21       0.1
4709  2010-08-15       0.1
4710  2010-08-14       0.1
4716  2010-08-08       0.1
4717  2010-08-07       0.1
4723  2010-08-01       0.1
4724  2010-07-31       0.1
4730  2010-07-25       0.1
4731  2010-07-24       0.1
4737  2010-07-18       0.0

Вывод: часть дат не совпала, потому что у Биткоина и золота разный календарь торгов, золото не торгуется по выходным. А так же часть не совпала, потому что данные по золоту до 2022 года, а по Биткоину до 2023 года.